<?php

namespace Database\Seeders;

use App\Models\Topic;
use App\Models\Question;
use App\Models\Answer;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $data = [

            'html' => [
                ['q' => 'What does HTML stand for?',
                    'a' => ['HyperText Markup Language', 'HighText Machine Language', 'HyperText Machine Language', 'HyperTool Markup Language'], 'c' => 'HyperText Markup Language'],
                ['q' => 'Which tag is used to create a hyperlink in HTML?',
                    'a' => ['<a>', '<link>', '<href>', '<url>'], 'c' => '<a>'],
                ['q' => 'Which tag is used for the largest heading in HTML?',
                    'a' => ['<h1>', '<h6>', '<heading>', '<head>'], 'c' => '<h1>'],
                ['q' => 'What tag is used to insert an image?',
                    'a' => ['<img>', '<image>', '<pic>', '<src>'], 'c' => '<img>'],
                ['q' => 'Which HTML element defines the body of a document?',
                    'a' => ['<body>', '<main>', '<content>', '<div>'], 'c' => '<body>'],
                ['q' => 'What attribute specifies the URL of a link?',
                    'a' => ['href', 'src', 'url', 'link'], 'c' => 'href'],
                ['q' => 'Which tag creates an unordered list?',
                    'a' => ['<ul>', '<ol>', '<li>', '<list>'], 'c' => '<ul>'],
                ['q' => 'What does the <br> tag do?',
                    'a' => ['Inserts a line break', 'Bolds text', 'Creates a border', 'Breaks a table'], 'c' => 'Inserts a line break'],
                ['q' => 'Which tag is used to define a table row?',
                    'a' => ['<tr>', '<td>', '<th>', '<row>'], 'c' => '<tr>'],
                ['q' => 'What tag wraps the visible content of an HTML page?',
                    'a' => ['<body>', '<html>', '<main>', '<section>'], 'c' => '<body>'],
                ['q' => 'Which HTML tag is used to define internal CSS?',
                    'a' => ['<style>', '<css>', '<script>', '<link>'], 'c' => '<style>'],
                ['q' => 'What does the <title> tag do?',
                    'a' => ['Sets the browser tab title', 'Creates a heading', 'Adds a tooltip', 'Defines metadata'], 'c' => 'Sets the browser tab title'],
                ['q' => 'Which attribute is used to add a tooltip to an element?',
                    'a' => ['title', 'tooltip', 'alt', 'label'], 'c' => 'title'],
                ['q' => 'What tag is used to make text bold in HTML?',
                    'a' => ['<b>', '<bold>', '<strong>', '<em>'], 'c' => '<b>'],
                ['q' => 'Which tag defines a paragraph in HTML?',
                    'a' => ['<p>', '<para>', '<text>', '<div>'], 'c' => '<p>'],
            ],

            'laravel' => [
                ['q' => 'What command creates a new Laravel project?',
                    'a' => ['composer create-project laravel/laravel', 'laravel new project', 'php artisan new', 'npm create laravel'], 'c' => 'composer create-project laravel/laravel'],
                ['q' => 'What is the default ORM used in Laravel?',
                    'a' => ['Eloquent', 'Doctrine', 'Propel', 'RedBean'], 'c' => 'Eloquent'],
                ['q' => 'Which command runs database migrations?',
                    'a' => ['php artisan migrate', 'php artisan db:migrate', 'php artisan run:migration', 'php artisan migration:run'], 'c' => 'php artisan migrate'],
                ['q' => 'What file defines Laravel application routes?',
                    'a' => ['routes/web.php', 'app/routes.php', 'config/routes.php', 'http/routes.php'], 'c' => 'routes/web.php'],
                ['q' => 'What does the "php artisan tinker" command do?',
                    'a' => ['Opens an interactive REPL', 'Runs tests', 'Clears the cache', 'Starts the server'], 'c' => 'Opens an interactive REPL'],
                ['q' => 'Which templating engine does Laravel use by default?',
                    'a' => ['Blade', 'Twig', 'Smarty', 'Mustache'], 'c' => 'Blade'],
                ['q' => 'What is Laravel Horizon used for?',
                    'a' => ['Monitoring Redis queues', 'Database backups', 'Email sending', 'File storage'], 'c' => 'Monitoring Redis queues'],
                ['q' => 'What method is used to define a one-to-many relationship in Eloquent?',
                    'a' => ['hasMany()', 'belongsTo()', 'hasOne()', 'belongsToMany()'], 'c' => 'hasMany()'],
                ['q' => 'Which command generates a new controller?',
                    'a' => ['php artisan make:controller', 'php artisan create:controller', 'php artisan new:controller', 'php artisan controller:make'], 'c' => 'php artisan make:controller'],
                ['q' => 'What is the purpose of Laravel middleware?',
                    'a' => ['Filter HTTP requests', 'Define database schema', 'Send emails', 'Compile assets'], 'c' => 'Filter HTTP requests'],
                ['q' => 'Which command creates a new Eloquent model?',
                    'a' => ['php artisan make:model', 'php artisan create:model', 'php artisan model:new', 'php artisan generate:model'], 'c' => 'php artisan make:model'],
                ['q' => 'What does "php artisan migrate:fresh" do?',
                    'a' => ['Drops all tables and re-runs migrations', 'Only runs new migrations', 'Rolls back last migration', 'Seeds the database'], 'c' => 'Drops all tables and re-runs migrations'],
                ['q' => 'Where are Blade templates stored in Laravel?',
                    'a' => ['resources/views', 'app/views', 'public/views', 'storage/views'], 'c' => 'resources/views'],
                ['q' => 'What is the default session driver in Laravel?',
                    'a' => ['file', 'database', 'cookie', 'redis'], 'c' => 'file'],
                ['q' => 'Which Laravel facade is used to interact with the database directly?',
                    'a' => ['DB', 'Schema', 'Eloquent', 'Query'], 'c' => 'DB'],
            ],

            'php' => [
                ['q' => 'What does PHP stand for?',
                    'a' => ['PHP: Hypertext Preprocessor', 'Personal Home Page', 'Preprocessed Hypertext Pages', 'Private Hypertext Protocol'], 'c' => 'PHP: Hypertext Preprocessor'],
                ['q' => 'Which symbol is used to declare a variable in PHP?',
                    'a' => ['$', '@', '#', '&'], 'c' => '$'],
                ['q' => 'What function is used to output text in PHP?',
                    'a' => ['echo', 'print_text', 'output', 'display'], 'c' => 'echo'],
                ['q' => 'Which of these is the correct way to start a PHP block?',
                    'a' => ['<?php', '<php>', '<?', '<script php>'], 'c' => '<?php'],
                ['q' => 'What does the "===" operator check in PHP?',
                    'a' => ['Value and type equality', 'Value equality only', 'Type equality only', 'Reference equality'], 'c' => 'Value and type equality'],
                ['q' => 'Which function returns the length of a string in PHP?',
                    'a' => ['strlen()', 'length()', 'strcount()', 'count()'], 'c' => 'strlen()'],
                ['q' => 'What is a PHP trait used for?',
                    'a' => ['Code reuse across classes', 'Database connections', 'Error handling', 'Session management'], 'c' => 'Code reuse across classes'],
                ['q' => 'Which superglobal holds form POST data?',
                    'a' => ['$_POST', '$_FORM', '$_INPUT', '$_REQUEST_POST'], 'c' => '$_POST'],
                ['q' => 'What does the "null coalescing operator" (??) do?',
                    'a' => ['Returns right side if left is null', 'Checks for empty strings', 'Converts null to false', 'Merges two arrays'], 'c' => 'Returns right side if left is null'],
                ['q' => 'Which function merges two arrays in PHP?',
                    'a' => ['array_merge()', 'merge_array()', 'array_combine()', 'array_push()'], 'c' => 'array_merge()'],
                ['q' => 'What does "var_dump()" do in PHP?',
                    'a' => ['Outputs variable type and value', 'Deletes a variable', 'Copies a variable', 'Converts variable to string'], 'c' => 'Outputs variable type and value'],
                ['q' => 'Which loop runs at least once regardless of condition?',
                    'a' => ['do-while', 'while', 'for', 'foreach'], 'c' => 'do-while'],
                ['q' => 'How do you start a comment in PHP?',
                    'a' => ['//', '##', '**', '<!--'], 'c' => '//'],
                ['q' => 'What is the correct way to create a function in PHP?',
                    'a' => ['function myFunc() {}', 'def myFunc() {}', 'func myFunc() {}', 'create myFunc() {}'], 'c' => 'function myFunc() {}'],
                ['q' => 'Which superglobal stores session data in PHP?',
                    'a' => ['$_SESSION', '$_COOKIE', '$_SERVER', '$_GLOBAL'], 'c' => '$_SESSION'],
            ],

            'vtdt' => [
                ['q' => 'Kā pilnībā sauc VTDT?',
                    'a' => ['Vidzemes Tehnoloģiju un dizaina tehnikums', 'Valmieras Tehnoloģiju un dizaina tehnikums', 'Vidzemes Tirdzniecības un dizaina tehnikums', 'Vidzemes Tehnikas un datoru tehnikums'], 'c' => 'Vidzemes Tehnoloģiju un dizaina tehnikums'],
                ['q' => 'Kur atrodas VTDT?',
                    'a' => ['Valmierā', 'Rīgā', 'Cēsīs', 'Siguldā'], 'c' => 'Valmierā'],
                ['q' => 'Kāds ir VTDT mājas lapas domēns?',
                    'a' => ['vtdt.lv', 'vtdt.edu.lv', 'vidzeme-tehnikums.lv', 'vdt.lv'], 'c' => 'vtdt.lv'],
                ['q' => 'Ko piedāvā VTDT pēc pamatskolas?',
                    'a' => ['Profesionālo izglītību ar vidējo izglītību', 'Tikai vidējo izglītību', 'Tikai kursus', 'Augstāko izglītību'], 'c' => 'Profesionālo izglītību ar vidējo izglītību'],
                ['q' => 'Kas ir SkillsLatvia?',
                    'a' => ['Profesionālās meistarības konkurss', 'Sporta sacensības', 'Programmēšanas olimpiāde', 'Mūzikas festivāls'], 'c' => 'Profesionālās meistarības konkurss'],
                ['q' => 'Ko var atrast VTDT dienesta viesnīcā?',
                    'a' => ['Dzīvesvietu audzēkņiem', 'Restorānu', 'Sporta zāli', 'Bibliotēku'], 'c' => 'Dzīvesvietu audzēkņiem'],
                ['q' => 'Kādas mācības piedāvā VTDT pieaugušajiem?',
                    'a' => ['Profesionālās pilnveides kursus', 'Tikai valodu kursus', 'Bakalaura programmas', 'Sporta treniņus'], 'c' => 'Profesionālās pilnveides kursus'],
                ['q' => 'VTDT ieguva kādas medaļas SkillsLatvia 2026?',
                    'a' => ['Zeltu un bronzu', 'Sudrabu un bronzu', 'Tikai zeltu', 'Nevienu'], 'c' => 'Zeltu un bronzu'],
                ['q' => 'Ko nozīmē VTDT devīze "vieta, kur kļūt par profesionāli"?',
                    'a' => ['Skola sagatavo audzēkņus darba tirgum', 'Skola māca tikai hobijus', 'Skola ir tikai vidusskola', 'Skola piedāvā tikai sportu'], 'c' => 'Skola sagatavo audzēkņus darba tirgum'],
                ['q' => 'Ko VTDT piedāvā karjeras atbalsta ietvaros?',
                    'a' => ['Karjeras konsultanta pakalpojumus', 'Darba vietas', 'Stipendijas visiem', 'Bezmaksas transportu'], 'c' => 'Karjeras konsultanta pakalpojumus'],
                ['q' => 'Kur var atrast VTDT stundu sarakstu?',
                    'a' => ['vtdt.lv mājas lapā', 'Facebook grupā', 'Uz skolas sienas', 'Tikai direktora kabinetā'], 'c' => 'vtdt.lv mājas lapā'],
                ['q' => 'Ko VTDT piedāvā sporta bāzē?',
                    'a' => ['Sporta aktivitātes audzēkņiem', 'Peldbaseinu', 'Tenisa korti', 'Golfa laukumu'], 'c' => 'Sporta aktivitātes audzēkņiem'],
                ['q' => 'Ko nozīmē "agrā uzņemšana" VTDT?',
                    'a' => ['Iespēja pieteikties studijām agrāk', 'Mācības no rīta', 'Bezmaksas ēdināšana', 'Īpašas stipendijas'], 'c' => 'Iespēja pieteikties studijām agrāk'],
                ['q' => 'Kā sauc VTDT audzēkņu pārstāvību?',
                    'a' => ['Pašpārvalde', 'Studentu padome', 'Skolas parlaments', 'Jauniešu birojs'], 'c' => 'Pašpārvalde'],
                ['q' => 'Ko VTDT piedāvā sadaļā "Pulciņi"?',
                    'a' => ['Ārpusstundu aktivitātes un interešu izglītību', 'Papildus mācību stundas', 'Sporta sacensības', 'Valodu kursus'], 'c' => 'Ārpusstundu aktivitātes un interešu izglītību'],
            ],

            'ipb24' => [
                ['q' => 'How many students are in our class?',
                    'a' => ['20', '67', '42', '24', '18'], 'c' => '20'],
                ['q' => 'Who is the best programmer?',
                    'a' => ['Pēteris', 'Niks', 'Patriks', 'Mikls', 'Daniels'], 'c' => 'Mikls'],
                ['q' => 'How much on average in class your personal belongings "dissapear"?',
                    'a' => ['1', '2', '3'], 'c' => '2'],
                ['q' => 'How many people wear glasses?',
                    'a' => ['7', '11', '15', '6'], 'c' => '11'],
                ['q' => 'Can YOU "gurķoties" at Krīgerts classes?',
                    'a' => ['Yes', 'No'], 'c' => 'No'],
                ['q' => 'Can YOU "gurķoties" at Thomas Krieviņš classes?',
                    'a' => ['Yes', 'No', 'HZ'], 'c' => 'Yes'],
                ['q' => 'Average Donalds Mežulis income salary from depozīts?',
                    'a' => ['0.5e', '6.7e', '4.20e', '2.5e'], 'c' => '0.5e'],
                ['q' => 'Do you LIKE Ronis?',
                    'a' => ['Yes', 'No'], 'c' => 'No'],
                ['q' => 'Saimona tevi spīdzina?',
                    'a' => ['Ofc', 'Baig ne', 'Viņai liekas, ka jaa'], 'c' => 'Viņai liekas, ka jaa'],
                ['q' => 'What happens, when you look at Reinis?',
                    'a' => ['Reinis smiles', 'Reinis looks angry', 'Reinis didn\'t see you'], 'c' => 'Reinis smiles'],
                ['q' => 'What happens, when you ask Olengnovičš (Oliņš Boliņš) the time on his watch?',
                    'a' => ['"Go fuck yourself"', 'Viņš pats nezin', 'Viņš actually pasaka (wow)'], 'c' => 'Viņš actually pasaka (wow)'],
                ['q' => 'Average Enerģiskie bought day (Monster) for the whole class?',
                    'a' => ['2', '5', '9', 'I don\'t know'], 'c' => '5'],
                ['q' => 'How much wach was in your class in first year?',
                    'a' => ['Around 30+ people', 'Around 27+ people', 'Anšļāvs Eglītis'], 'c' => 'Around 30+ people'],
                ['q' => 'Biggest gooner in da class?',
                    'a' => ['Egīls', 'Vanessa', 'Peter', 'Zigmārs'], 'c' => 'Egīls'],
                ['q' => 'Who in the class was almost blind?',
                    'a' => ['Intars', 'Didzis', 'Vanesa'], 'c' => 'Intars'],
            ],

            'underground-music' => [
                ['q' => 'Kurš ir Bladee īstais vārds?',
                    'a' => ['Benjamin Reichwald', 'Karl Andersson', 'Erik Bowman', 'Simon Johansson'], 'c' => 'Benjamin Reichwald'],
                ['q' => 'Kādā gadā tika dibināta Drain Gang?',
                    'a' => ['2013', '2010', '2015', '2008'], 'c' => '2013'],
                ['q' => 'Kurš underground mākslinieks ir pazīstams ar albumu "Psychic 9-5 Club"?',
                    'a' => ['Yung Lean', 'Bladee', 'Ecco2k', 'Thaiboy Digital'], 'c' => 'Ecco2k'],
                ['q' => 'Kā sauc Yung Lean pirmo viral hitu?',
                    'a' => ['Ginseng Strip 2002', 'Hurt', 'Kyoto', 'Warlord'], 'c' => 'Ginseng Strip 2002'],
                ['q' => 'Kurš žanrs apvieno cloud rap un emo?',
                    'a' => ['Emo rap', 'Drill', 'Trap', 'Lo-fi'], 'c' => 'Emo rap'],
                ['q' => 'Ko nozīmē "DIY" mūzikas industrijā?',
                    'a' => ['Do It Yourself — patstāvīga mūzikas izdošana', 'Digital Indie Yarn', 'Direct Industry Yes', 'Distribute It Yourself'], 'c' => 'Do It Yourself — patstāvīga mūzikas izdošana'],
                ['q' => 'Kurš mākslinieks ir pazīstams ar albumu "444 No Mercy"?',
                    'a' => ['Bladee', 'Yung Lean', 'Thaiboy Digital', 'Ecco2k'], 'c' => 'Bladee'],
                ['q' => 'Kāds ir SoundCloud rap galvenais platforma?',
                    'a' => ['SoundCloud', 'Spotify', 'Apple Music', 'YouTube'], 'c' => 'SoundCloud'],
                ['q' => 'Kurš producents strādāja ar early Yung Lean?',
                    'a' => ['Yung Sherman', 'Metro Boomin', 'Pi\'erre Bourne', 'Wheezy'], 'c' => 'Yung Sherman'],
                ['q' => 'Ko nozīmē "lo-fi" mūzikā?',
                    'a' => ['Zemas kvalitātes skaņas ieraksts ar nolūku', 'Ļoti skaļa mūzika', 'Live only format', 'Long format'], 'c' => 'Zemas kvalitātes skaņas ieraksts ar nolūku'],
                ['q' => 'Kura pilsēta ir slavena ar underground drill scēnu?',
                    'a' => ['Čikāga', 'Losandželosa', 'Maiami', 'Atlanta'], 'c' => 'Čikāga'],
                ['q' => 'Kurš ir Ecco2k pilnais vārds?',
                    'a' => ['Zak Arogundade', 'Erik Bowman', 'Karl Berg', 'Simon Lindh'], 'c' => 'Zak Arogundade'],
                ['q' => 'Kāds žanrs ir saistīts ar "witch house"?',
                    'a' => ['Dark electronic ar okultiem elementiem', 'Country mūzika', 'Jazz fusion', 'K-pop'], 'c' => 'Dark electronic ar okultiem elementiem'],
                ['q' => 'Kurš underground kolektīvs ir pazīstams ar zilajām estētikām?',
                    'a' => ['Drain Gang', 'ASAP Mob', 'Odd Future', 'Pro Era'], 'c' => 'Drain Gang'],
                ['q' => 'Ko nozīmē "based" sleng underground mūzikā?',
                    'a' => ['Autentisks, bezcompromisu stils', 'Basa skaņa', 'Baida bāze', 'Baseline audio production'], 'c' => 'Autentisks, bezcompromisu stils'],
            ],

            'history' => [
                ['q' => 'Who was the first President of the United States?',
                    'a' => ['George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'], 'c' => 'George Washington'],
                ['q' => 'In which year did World War II end?',
                    'a' => ['1945', '1943', '1947', '1939'], 'c' => '1945'],
                ['q' => 'Which ancient wonder was located in Alexandria?',
                    'a' => ['The Lighthouse', 'The Colossus', 'The Hanging Gardens', 'The Statue of Zeus'], 'c' => 'The Lighthouse'],
                ['q' => 'Who was the first man to walk on the Moon?',
                    'a' => ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'], 'c' => 'Neil Armstrong'],
                ['q' => 'The Berlin Wall fell in which year?',
                    'a' => ['1989', '1991', '1985', '1979'], 'c' => '1989'],
                ['q' => 'Which empire was ruled by Julius Caesar?',
                    'a' => ['Roman Empire', 'Greek Empire', 'Ottoman Empire', 'Byzantine Empire'], 'c' => 'Roman Empire'],
                ['q' => 'What year did Christopher Columbus reach the Americas?',
                    'a' => ['1492', '1486', '1501', '1510'], 'c' => '1492'],
                ['q' => 'The French Revolution began in which year?',
                    'a' => ['1789', '1776', '1804', '1799'], 'c' => '1789'],
                ['q' => 'Who was the first female Prime Minister of the United Kingdom?',
                    'a' => ['Margaret Thatcher', 'Theresa May', 'Queen Elizabeth II', 'Liz Truss'], 'c' => 'Margaret Thatcher'],
                ['q' => 'Which country was the first to grant women the right to vote?',
                    'a' => ['New Zealand', 'United States', 'United Kingdom', 'Australia'], 'c' => 'New Zealand'],
                ['q' => 'Kurā gadā Latvija atguva neatkarību?',
                    'a' => ['1991', '1989', '1993', '1988'], 'c' => '1991'],
                ['q' => 'Who built the Great Wall of China?',
                    'a' => ['Emperor Qin Shi Huang', 'Emperor Han Wu', 'Genghis Khan', 'Kublai Khan'], 'c' => 'Emperor Qin Shi Huang'],
                ['q' => 'Which war was fought between the North and South of America?',
                    'a' => ['Civil War', 'Revolutionary War', 'World War I', 'Mexican-American War'], 'c' => 'Civil War'],
                ['q' => 'Who was Napoleon Bonaparte?',
                    'a' => ['French military leader and emperor', 'Russian tsar', 'British general', 'Spanish king'], 'c' => 'French military leader and emperor'],
                ['q' => 'In which year did the Titanic sink?',
                    'a' => ['1912', '1910', '1915', '1920'], 'c' => '1912'],
            ],

            'popular-brands' => [
                ['q' => 'Kādā gadā tika dibināts McDonald\'s?',
                    'a' => ['1940', '1955', '1962', '1935'], 'c' => '1940'],
                ['q' => 'Kāds ir McDonald\'s slavenākais burgera nosaukums?',
                    'a' => ['Big Mac', 'Whopper', 'Quarter Pounder', 'McRoyal'], 'c' => 'Big Mac'],
                ['q' => 'Kura valsts ir Nike mājas zeme?',
                    'a' => ['ASV', 'Vācija', 'Japāna', 'Anglija'], 'c' => 'ASV'],
                ['q' => 'Ko nozīmē Apple logo — iekosts ābols?',
                    'a' => ['Zināšanas un kreativitāte', 'Veselīgs uzturs', 'Dabas mīlestība', 'Vienkāršs dizains'], 'c' => 'Zināšanas un kreativitāte'],
                ['q' => 'Kurā gadā tika dibināta Tesla?',
                    'a' => ['2003', '2008', '2010', '1999'], 'c' => '2003'],
                ['q' => 'Kāds ir Coca-Cola oriģinālās receptes noslēpums?',
                    'a' => ['Recepte ir slepena un glabājas seifā', 'Recepte ir publiska', 'Recepte ir patentēta', 'Receptes nav'], 'c' => 'Recepte ir slepena un glabājas seifā'],
                ['q' => 'Ko nozīmē "IKEA" nosaukums?',
                    'a' => ['Dibinātāja iniciāļi + mājas un fermas nosaukums', 'Zviedru vārds māja', 'Dizaina koncepcija', 'Produktu kods'], 'c' => 'Dibinātāja iniciāļi + mājas un fermas nosaukums'],
                ['q' => 'Kura spēļu konsole ir Sony produkts?',
                    'a' => ['PlayStation', 'Xbox', 'Nintendo Switch', 'Atari'], 'c' => 'PlayStation'],
                ['q' => 'Kurā gadā tika dibināts Google?',
                    'a' => ['1998', '2000', '1995', '2003'], 'c' => '1998'],
                ['q' => 'Kāds ir Adidas logo?',
                    'a' => ['Trīs svītras', 'Ķeksītis', 'Pusloks', 'Zvaigzne'], 'c' => 'Trīs svītras'],
                ['q' => 'Kura kompānija ražo iPhone?',
                    'a' => ['Apple', 'Samsung', 'Google', 'Huawei'], 'c' => 'Apple'],
                ['q' => 'Kas ir McDonald\'s maskots?',
                    'a' => ['Ronald McDonald', 'Grimace', 'Hamburglar', 'Mayor McCheese'], 'c' => 'Ronald McDonald'],
                ['q' => 'Kādā gadā Starbucks atvēra pirmo kafejnīcu?',
                    'a' => ['1971', '1980', '1965', '1990'], 'c' => '1971'],
                ['q' => 'Ko ražo Lamborghini?',
                    'a' => ['Sporta automobiļus', 'Traktorus un sporta automobiļus', 'Lidmašīnas', 'Motociklus'], 'c' => 'Traktorus un sporta automobiļus'],
                ['q' => 'Kur atrodas LEGO galvenais birojs?',
                    'a' => ['Dānijā', 'Zviedrijā', 'Nīderlandē', 'Norvēģijā'], 'c' => 'Dānijā'],
            ],

            'koju-dzive' => [
                ['q' => 'What happens if you steal Pelmeņi from someone specifically in Prekuļi?',
                    'a' => ['You get an*l raped', 'Tevi samet', 'Viss okej'], 'c' => 'Tevi samet'],
                ['q' => 'Pulkstenis sit 00:00, ko tu dzirdi?',
                    'a' => ['Petardes', 'Muzika', 'Blausana', 'Skalas misenes', 'All of the above'], 'c' => 'All of the above'],
                ['q' => 'Cik biezi spragst podi Prekulos?',
                    'a' => ['Reizi mēnesī', 'Reizi gadsimta (kad uzrodas turbo daunis)', 'Katru dienu'], 'c' => 'Reizi gadsimta (kad uzrodas turbo daunis)'],
                ['q' => 'Cik staffins (gabalos) izlido pa logu ārā kad notiek reids?',
                    'a' => ['1', '150+', '50'], 'c' => '150+'],
                ['q' => 'Cik iespējams pēc kā ieiet tualetē nenomirstot?',
                    'a' => ['1%', '4%', 'Tu nomirsi jebkurā gadījumā'], 'c' => '1%'],
                ['q' => 'Cik maksā kojas (Prekuļi)?',
                    'a' => ['12.50', '15.50', '2.50'], 'c' => '2.50'],
                ['q' => 'Tev blakus dzīvo pervaki, ko tu dari?',
                    'a' => ['Samet viņus', 'Pizgi misonus', 'Sit ar cibam', 'All of the above'], 'c' => 'All of the above'],
                ['q' => 'Cik cilvēkus Prekuļos izmeta no kojām (2026)?',
                    'a' => ['10 aptuveni', '3', 'Nevienu'], 'c' => '10 aptuveni'],
                ['q' => 'Cik cilvēkus reidā piekēra (Saules iela)?',
                    'a' => ['40%', '20%', '10%'], 'c' => '40%'],
                ['q' => 'Cik procentuāli gurķi ir kojās?',
                    'a' => ['Jā', '50%', '80%'], 'c' => 'Jā'],
                ['q' => 'Vai tev patīk dzīvot kojās? (ja nedzīvo neatbildi.)',
                    'a' => ['Jā', 'Man nav izvēles..', 'Nē'], 'c' => 'Man nav izvēles..'],
                ['q' => 'Cik biezi tev snapa pievienojas fujaki no kojam lai censtos tev kko pardot?',
                    'a' => ['Daudz', 'Mazs', 'Vidēji'], 'c' => 'Daudz'],
                ['q' => 'Ko šie fujaki tev censas pardot?',
                    'a' => ['Puffi', 'Absolutely jebko', 'Koju siera touch', 'Znuz'], 'c' => 'Absolutely jebko'],
                ['q' => 'Cik cilvēki saka, ka nemāk spēlēt novusu un pēc tam tevi iz*aro?',
                    'a' => ['2', 'Vismaz 50%', '67'], 'c' => 'Vismaz 50%'],
                ['q' => 'Gurkis gurkojas gurk kojās?',
                    'a' => ['gurk', 'gurkis', 'Jā, vienmēr', 'Nē'], 'c' => 'gurk'],
            ],

            'gaming' => [
                ['q' => 'Kurā gadā tika izlaista pirmā Grand Theft Auto spēle?',
                    'a' => ['1997', '2001', '1995', '1999'], 'c' => '1997'],
                ['q' => 'Kura spēle ir vispārdotākā visu laiku?',
                    'a' => ['Minecraft', 'Tetris', 'GTA V', 'Wii Sports'], 'c' => 'Minecraft'],
                ['q' => 'Ko nozīmē "FPS" spēlēs?',
                    'a' => ['First Person Shooter', 'Frames Per Second', 'Abi', 'Fast Pace System'], 'c' => 'Abi'],
                ['q' => 'Kurā gadā tika izlaista Fortnite?',
                    'a' => ['2017', '2015', '2019', '2016'], 'c' => '2017'],
                ['q' => 'Kas ir "Mario" pilnais vārds?',
                    'a' => ['Mario Mario', 'Mario Luigi', 'Mario Bros', 'Super Mario'], 'c' => 'Mario Mario'],
                ['q' => 'Kura kompānija izstrādāja The Witcher 3?',
                    'a' => ['CD Projekt Red', 'Bethesda', 'Ubisoft', 'EA Games'], 'c' => 'CD Projekt Red'],
                ['q' => 'Kas ir "MOBA" žanrs?',
                    'a' => ['Multiplayer Online Battle Arena', 'Mobile Online Battle Arena', 'Massive Online Battle Arena', 'Modern Online Battle Arena'], 'c' => 'Multiplayer Online Battle Arena'],
                ['q' => 'Kurā valstī tika dibināts Nintendo?',
                    'a' => ['Japānā', 'ASV', 'Korejā', 'Ķīnā'], 'c' => 'Japānā'],
                ['q' => 'Kāds ir Counter-Strike galvenais mērķis?',
                    'a' => ['Bumba/ķīlnieki taktiskā komandu spēle', 'Battle royale', 'Open world RPG', 'Racing'], 'c' => 'Bumba/ķīlnieki taktiskā komandu spēle'],
                ['q' => 'Ko nozīmē "GG" gēmeru valodā?',
                    'a' => ['Good Game', 'Great Goal', 'Go Go', 'Game Gone'], 'c' => 'Good Game'],
                ['q' => 'Kurā gadā tika izlaista pirmā PlayStation?',
                    'a' => ['1994', '1990', '1998', '1996'], 'c' => '1994'],
                ['q' => 'Kura spēle ir pazīstama ar frāzi "The cake is a lie"?',
                    'a' => ['Portal', 'Half-Life', 'Minecraft', 'Among Us'], 'c' => 'Portal'],
                ['q' => 'Ko nozīmē "RPG" spēlēs?',
                    'a' => ['Role Playing Game', 'Random Player Game', 'Real Play Game', 'Rocket Propelled Game'], 'c' => 'Role Playing Game'],
                ['q' => 'Kurā gadā tika izlaists Minecraft?',
                    'a' => ['2011', '2009', '2013', '2007'], 'c' => '2011'],
                ['q' => 'Kas ir "Among Us" spēles mērķis?',
                    'a' => ['Atrast impostoru komandā', 'Nogalināt visus', 'Uzbūvēt kosmosa kuģi', 'Izdzīvot zombiju apokalipsē'], 'c' => 'Atrast impostoru komandā'],
            ],

        ];

        foreach ($data as $slug => $questions) {
            $topic = Topic::where('slug', $slug)->first();
            if (!$topic) continue;

            $topic->questions()->each(fn($q) => $q->answers()->delete());
            $topic->questions()->delete();

            foreach ($questions as $item) {
                $question = Question::create([
                    'topic_id'      => $topic->id,
                    'question_text' => $item['q'],
                ]);

                foreach ($item['a'] as $answerText) {
                    Answer::create([
                        'question_id' => $question->id,
                        'answer_text' => $answerText,
                        'is_correct'  => $answerText === $item['c'],
                    ]);
                }
            }
        }
    }
}
